IF (HIREDIS_USE_STATIC_LIBS)
  SET (CMAKE_FIND_LIBRARY_SUFFIXES .a)
ENDIF ()

FIND_PATH (HIREDIS_INCLUDE_DIR NAMES hiredis/hiredis.h PATH_SUFFIXES include)
FIND_LIBRARY (HIREDIS_LIBRARY NAMES hiredis)

IF (HIREDIS_INCLUDE_DIR AND EXISTS "${HIREDIS_INCLUDE_DIR}/hiredis/hiredis.h")
    FILE (STRINGS "${HIREDIS_INCLUDE_DIR}/hiredis/hiredis.h" VERSION_STRING REGEX "^#define HIREDIS_MAJOR [0-9]+$")
    STRING (REGEX REPLACE "^#define HIREDIS_MAJOR ([0-9]+)$" "\\1" HIREDIS_VERSION_MAJOR "${VERSION_STRING}")

    FILE (STRINGS "${HIREDIS_INCLUDE_DIR}/hiredis/hiredis.h" VERSION_STRING REGEX "^#define HIREDIS_MINOR [0-9]+$")
    STRING (REGEX REPLACE "^#define HIREDIS_MINOR ([0-9]+)$" "\\1" HIREDIS_VERSION_MINOR "${VERSION_STRING}")

    FILE (STRINGS "${HIREDIS_INCLUDE_DIR}/hiredis/hiredis.h" VERSION_STRING REGEX "^#define HIREDIS_PATCH [0-9]+$")
    STRING (REGEX REPLACE "^#define HIREDIS_PATCH ([0-9]+)$" "\\1" HIREDIS_VERSION_PATCH "${VERSION_STRING}")

    SET (HIREDIS_VERSION ${HIREDIS_VERSION_MAJOR}.${HIREDIS_VERSION_MINOR}.${HIREDIS_VERSION_PATCH})
    UNSET (VERSION_STRING)
ENDIF ()

INCLUDE (FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS (Hiredis
    REQUIRED_VARS HIREDIS_LIBRARY HIREDIS_INCLUDE_DIR
    VERSION_VAR HIREDIS_VERSION
)
