IF (CppDB_USE_STATIC_LIBS)
  SET (CMAKE_FIND_LIBRARY_SUFFIXES .a)
ENDIF ()

FIND_PATH (CppDB_INCLUDE_DIR NAMES cppdb/defs.h PATH_SUFFIXES include)
FIND_LIBRARY (CppDB_LIBRARY NAMES cppdb)
FIND_LIBRARY (CppDB_Postgres_LIBRARY NAMES cppdb_postgresql)

INCLUDE (FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS (CppDB
    REQUIRED_VARS CppDB_INCLUDE_DIR CppDB_LIBRARY
)
